sonar.projectKey=luskation_devsecops-aws-pipeline
sonar.organization=luskation

# Diretório principal analisado pelo SonarCloud. Mantém a análise focada apenas no código-fonte.
sonar.sources=src

sonar.sourceEncoding=UTF-8